version: 2.1

jobs:
  release:
    working_directory: ~/mixed-monorepo-php
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Run semantic release
          command: npx semantic-release


workflows:
  version: 2

  release:
    jobs:
      - release:
          filters:
            branches:
              only:
                - master
